export type MethodDefinition = {
  id: string;
  term: string;
  shownAs: string;
  plain: string;
  howToRead: string;
  formula?: string;
};

export const METHODS_DEFINITIONS: MethodDefinition[] = [
  { id: "reportedIncidentRate", term: "Exposure-adjusted rate", shownAs: "12 /yr",
    plain: "Direct place-to-place Compare uses reported-event density per square kilometre per day, displayed as a full year inside your circle. With a window shorter than a year this is an extrapolation, not an observed count. Single-place local context uses observed equal-window counts instead.",
    howToRead: "A density used for direct Compare, not a per-person or per-visit rate.", formula: "per-year = incidents ÷ days × 365.25" },
  { id: "referenceCircles", term: "Reference circles", shownAs: "MCPP · sector · citywide",
    plain: "The selected place is compared with the observed counts around eligible Seattle street-segment midpoints. Every comparison circle uses the same radius, dates, layer, and filters. Incidents stay at their observed coordinates; geography chooses comparison centers and never spreads reports evenly across an area.",
    howToRead: "The median and ranges describe what the observed map contains around eligible street locations." },
  { id: "referenceFrame", term: "Street-segment sampling frame", shownAs: "eligible centers",
    plain: "One versioned midpoint represents each open public Seattle street segment in the City street network. MCPP and sector boundary circles mix their reference locations according to the share of the selected circle in each geography.",
    howToRead: "A typical eligible street segment—not a typical resident, business, visit, parcel, or square metre." },
  { id: "referenceRange", term: "Empirical reference range", shownAs: "10th–90th · middle 50%",
    plain: "The line spans the 10th through 90th percentiles of equal-radius reference counts; the band is the middle 50%; the median is the center line; and the dot is this place's observed count. Fewer, same, and more are reported separately because count ties are common.",
    howToRead: "A descriptive position in the reference frame, not a significance test or expected-crime estimate." },
  { id: "referenceComputation", term: "Exact / Monte Carlo", shownAs: "all centers · 2,500 draws",
    plain: "Small reference populations are evaluated completely. Larger populations use a deterministic 2,500-draw approximation from the same versioned center frame. The displayed margin describes simulation precision only, not uncertainty about crime or personal risk.",
    howToRead: "Repeated runs with the same location and radius use the same comparison-center sample." },
  { id: "rateRatio", term: "Rate ratio", shownAs: "4.0×",
    plain: "In direct place-to-place Compare, how many times one selected place's density sits above or below another's.",
    howToRead: "Used for selected-place comparisons, not the single-place reference-circle rows." },
  { id: "absoluteRateInterval", term: "Absolute-rate interval", shownAs: "4.2–8.1 /yr",
    plain: "The range around one place's own reported-density rate, rescaled to expected reports per year inside the selected radius. It describes that one rate; it is not the interval for a rate ratio against another place or baseline.",
    howToRead: "This is the bar around a place's dot. It is not adjusted for multiple comparisons." },
  { id: "confidenceInterval", term: "Rate-ratio interval", shownAs: "2.1–7.6×",
    plain: "The plausible range for the ratio between a place and a comparator. Absolute-rate and rate-ratio intervals both use a large-sample Wald form on the log scale, widened with Student-t because burstiness φ is estimated from a handful of months. Coverage is near, not exactly, 95%, and calibration fell to about 89% with very bursty, small counts.",
    howToRead: "Shown in analytical detail. The interval is not adjusted for multiple comparisons; the verdict uses the adjusted p-value and also requires the ratio past 1.25× / 0.8×. Wider = less certain." },
  { id: "adjustedPValue", term: "Statistically clear", shownAs: "the verdict badge",
    plain: "Within each direct place-to-place Compare run, this says whether the candidate differs enough from every other selected place after Benjamini–Hochberg adjustment across that run's candidate-vs-other tests. Separate runs are not adjusted together. Single-place reference circles are descriptive and have no p-value.",
    howToRead: "For direct Compare, clear means adjusted p < 0.05 and the ratio is past 1.25× / 0.8×." },
  { id: "overdispersion", term: "Dispersion φ / quasi-Poisson", shownAs: "φ 1.4",
    plain: "We always widen intervals by the measured burstiness (φ), never narrowing below plain Poisson; above φ 1.2 the method is labeled quasi-Poisson. Because φ is estimated from a handful of months, intervals use a Student-t multiplier.",
    howToRead: "Higher φ = burstier reports, wider intervals." },
  { id: "minimumDataStatus", term: "Data adequacy", shownAs: "insufficient data",
    plain: "Direct Compare requires at least 30 days, at least 3 incidents per selected place, at least 10 across each tested pair, positive exposure, and enough months to fit dispersion. Reference-circle context separately requires at least 100 eligible centers and 80% mapped-circle coverage for MCPP or sector; an unavailable local row falls back to sector or city rather than inventing a comparator.",
    howToRead: "An unavailable row explains which requirement was not met." },
  { id: "nearestIncident", term: "Nearest incident", shownAs: "42 m",
    plain: "Distance to the closest matching reported incident.",
    howToRead: "Proximity only — not severity." },
  { id: "monthlyTrend", term: "Monthly trend", shownAs: "the sparkline",
    plain: "Reported incidents per month across the selected range.",
    howToRead: "Shape over time, not a forecast." },
  { id: "radiusMatters", term: "Radius matters", shownAs: "250 m / 500 m / 1000 m",
    plain: "Every result is radius-dependent by construction: the circle changes both the selected place's count and every reference-circle count. Larger circles can also mix more MCPPs or sectors.",
    howToRead: "Try several radii. A comparison at 250 m can legitimately differ at 1000 m." },
  { id: "manyLooks", term: "Many looks", shownAs: "filters, radii, layers",
    plain: "Scanning many filter combinations will surface an occasional 'clear' result by chance; the adjustment covers the tests within one run, not the runs you tried.",
    howToRead: "Treat a lone surprise across many looks with caution." },
  { id: "compareRanking", term: "Compare order", shownAs: "1 · 2 · 3 · lowest rate",
    plain: "The numbered order and lowest-rate chip are descriptive. The lowest observed rate is selected after looking at the data, so it is biased low by ordinary sampling noise.",
    howToRead: "Only an overall statistically lower verdict is a tested conclusion; the displayed order itself is not a statistical ranking." },
  { id: "nibrsGroup", term: "NIBRS group", shownAs: "NIBRS A",
    plain: "The FBI's National Incident-Based Reporting System classification SPD files each offense under. Group A covers the offenses reported in full detail; Group B covers a shorter list reported only when an arrest is made.",
    howToRead: "A filing category, not a severity ranking." },
];
